DROP INDEX IF EXISTS idx_actor_last_name CASCADE;

DROP INDEX IF EXISTS idx_actor_last_name CASCADE;

DROP INDEX IF EXISTS film_fulltext_idx CASCADE;

DROP INDEX IF EXISTS idx_fk_language_id CASCADE;

DROP INDEX IF EXISTS idx_title CASCADE;

DROP INDEX IF EXISTS idx_fk_film_id CASCADE;